[package]
name = "cubic-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { version = "1.1.0", optional = true }

[features]
tokio-bytes = ["dep:bytes"]