[package]
name = "bird-protocol-server"
version = "0.1.0"
edition = "2021"
description = "ProtocolServer for CubicProtocol"
license = "MIT"

[dependencies]
bird-protocol = "0.1.0"
async-trait = "0.1.56"
tokio = { version = "1.19.2", features = ["full"] }
log = "0.4.17"