[package]
name = "cubic-protocol-server"
version = "0.1.7"
edition = "2021"
description = "ProtocolServer for CubicProtocol"
license = "MIT"

[dependencies]
cubic-protocol = "0.1.7"
async-trait = "0.1.56"
tokio = { version = "1.19.2", features = ["full"] }
log = "0.4.17"