[package]
name = "cubic-protocol-server"
version = "0.1.6"
edition = "2021"
description = "ProtocolServer for CubicProtocol"
license = "MIT"

[dependencies]
cubic-protocol = { path = "../cubic_protocol" }
async-trait = "0.1.56"
tokio = { version = "1.19.2", features = ["full"] }
